### ISSUE TITLE
Visualization of style-diversified images

### ISSUE THREAD

**Issue by uiloqit** [HeliosZhao/SHADE-VisualDG#1]
Hi, in the MiT backbone, the diverse image features are generated by `shm`
https://github.com/HeliosZhao/SHADE-VisualDG/blob/954bfc4e2d5dbaca5ea9551a657cacf73478b660/sseg/mmseg/models/backbones/mix_transformer.py#L425

How can I visualize the style-diversified images from `x_tuple`, is there any related code for visualizing the images? 

Thanks for your help.

**Comment by HeliosZhao** [comment]
Hi, thanks for your interest in our work. We visualize the SHM in ResNet by adding a decoder after SHM, and train it as an autoencoder. You may refer to Sec 4.6 in our [paper](https://arxiv.org/abs/2212.09068) for details.

If you want to visualize SHM in MiT, i think you can just use the same way by adding a transformer-version decoder.
